### ISSUE TITLE
IronSeed will not run without sound support

### ISSUE THREAD

**Issue by nukebloodaxe** [nukebloodaxe/ironseed_fpc#3]
IronSeed currently requires a soundcard to play the game.  Now while the game is very reliant on sound to convey its atmosphere, I would still like the option to play the game without sound at all.  There are also practical reasons for having this, in that the laptop used for testing this build has recently had its sound chips die on it.

**Comment by mnalis** [comment]
That should be fixed now in https://github.com/mnalis/ironseed_fpc/issues/29
