### ISSUE TITLE
Out of Memory Error on restart

### ISSUE THREAD

**Issue by nukebloodaxe** [nukebloodaxe/ironseed_fpc#4]
Termination of IronSeed due to a bug can result in the situation where attempting to run IronSeed again will result in an immediate out of memory error, and the termination of IronSeed again. Waiting a reasonable amount of time can allow IronSeed to be run again, but this should really not be necessary.

Further investigation shows that running any of the non-core executables will immediately free whatever is causing the problem.  This suggests a possible thread problem, possibly a fork, or zombie.

**Comment by nukebloodaxe** [comment]
Interestingly simply quitting will produce the same effect.  This is going to be fun to track down.

**Comment by mnalis** [comment]
I could never reproduce this in versions after SDL multithreaded problems were solved... so I think this is probably fixed now
