### ISSUE TITLE
Graphics File Format

### ISSUE THREAD

**Issue by nukebloodaxe** [nukebloodaxe/ironseed_fpc#6]
Currently researching the graphics file format, and have an idea it was possibly produced using the Hijaak Graphics Suite.  There are, however, several other candidates including Corel products.  As all of this concerns systems around the 1990's things are going to be very difficult.

If I find a working copy of the graphics editor for the format used in IronSeed, I really think it will be prudent to update the graphics file format support to something much more modern and open.  Especially to save future coders serious grief.

**Comment by nukebloodaxe** [comment]
I have found the graphics assets in PNG format in an alternative IronSeed repository, which is the original DOS version released onto GitHub by the developer.  This will aid in either creating a PNG to cpr converter, or adjusting the game to load its assets in PNG.

However, this creates a trade-off, loading the assets in using PNG will use far more memory than usual, whereas the original cpr format will work in memory constrained environments.  I am leaning towards having a PNG to cpr converter because of that reason.

**Comment by nukebloodaxe** [comment]
All good, I've opened any that have been closing, so there will be no
problems there.  If you could, check the version.txt file in the Documents
folder, it would be cool if you added your improvements there too.
There is also the old ToDo list from the original developers which contains
some interesting insights into what they were doing/thinking of doing.

Regards,
Nuke.

**Comment by mnalis** [comment]
Here, I wrote few converters which should be able to convert to/from `.cpr` format. They are first version, but I hope they'll help.
I'm not quite sure about color palette though, and they won't work unless image is 320x200 in 8bpp palette. 

But I've tried it on few images from Ironseed `data/` directory, and they seems to work fine (except my image viewer tries to correct gamma by making it more or less bright)

**Comment by nukebloodaxe** [comment]
I noticed the current PNG images from one of the other repositories suffers from the same problem, so it's probably implicit in the conversion process.  These are really useful, want to make a pull request when you think they're ready?

**Comment by mnalis** [comment]
I think I managed to fix the palette color issue when converting images
